name: Deploy to DigitalOcean VPS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_SERVER_IP }}
        username: ${{ secrets.DO_SERVER_USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        script: |
          # Navigate to project directory
          cd /var/www/html/do
          
          # Fetch latest changes and reset to latest
          git fetch origin
          git reset --hard origin/main
          
          # Set correct permissions
          sudo chown -R www-data:www-data .
          sudo chmod -R 755 .
          
          # Optional: Run build commands if needed
          # npm install
          # npm run build
          
          # Restart web server if necessary
          sudo systemctl restart apache2
