name: Deploy to DigitalOcean VPS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_SERVER_IP }}
        username: ${{ secrets.DO_SERVER_USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        script: |
          # Ensure the directory exists
          mkdir -p /var/www/html/do
          
          # Remove existing content
          rm -rf /var/www/html/do/*
          
          # Copy files from GitHub Actions runner to server
          scp -r ${{ github.workspace }}/* ${{ secrets.DO_SERVER_USERNAME }}@${{ secrets.DO_SERVER_IP }}:/var/www/html/do/
          
          # Navigate to project directory
          cd /var/www/html/do
          
          # Set correct permissions
          sudo chown -R www-data:www-data .
          sudo chmod -R 755 .
          
          # Optional: Run build commands if needed
          # npm install
          # npm run build
          
          # Restart web server if necessary
          sudo systemctl restart apache2
