name: Deploy to DigitalOcean VPS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_SERVER_IP }}
        username: ${{ secrets.DO_SERVER_USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        script: |
          # Ensure git is installed
          sudo apt-get update
          sudo apt-get install -y git
          
          # Ensure the directory exists
          mkdir -p /var/www/html/do
          
          # Navigate to the directory
          cd /var/www/html/do
          
          # Clone or pull the repository
          if [ ! -d .git ]; then
            # Use GitHub Personal Access Token for cloning
            git clone https://${{ secrets.GITHUB_TOKEN }}@https://github.com/thev1ndu/do-workflow.git .
          else
            git pull origin main
          fi
          
          # Set correct permissions
          sudo chown -R www-data:www-data .
          sudo chmod -R 755 .
