name: Deploy to DigitalOcean VPS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_SERVER_IP }}
        username: ${{ secrets.DO_SERVER_USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        script: |
          # Update and install git
          sudo apt-get update
          sudo apt-get install -y git

          # Ensure project directory exists
          sudo mkdir -p /var/www/html/do
          
          # Change to project directory
          cd /var/www/html/do
          
          # Remove existing content
          sudo rm -rf *
          
          # Clone the entire repository
          sudo git clone https://github.com/thev1ndu/do-workflow.git .
          
          # Set proper permissions
          sudo chown -R www-data:www-data /var/www/html/do
          sudo chmod -R 755 /var/www/html/do
