name: Deploy to DigitalOcean VPS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_SERVER_IP }}
        username: ${{ secrets.DO_SERVER_USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        script: |
          # Ensure the directory exists
          mkdir -p /var/www/html/do
          
          # Navigate to the directory
          cd /var/www/html/do
          
          # If it's not a git repository, clone it first
          if [ ! -d .git ]; then
            git clone https://github.com/thev1ndu/do-workflow .
          fi
          
          # Pull latest changes
          git pull origin main
          
          # Set correct permissions
          sudo chown -R www-data:www-data .
          sudo chmod -R 755 .
          
          # Optional: Run build commands
          # npm install
          # npm run build
          
          # Restart web server if necessary
          sudo systemctl restart apache2
